name: Build
on:
  workflow_dispatch:
permissions:
  contents: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: dependencygraph
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: src/sdk
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: install deps
        run: pip install build
      - name: install apt deps
        run: |
          sudo apt-get update
          sudo apt-get install nasm -y
      - name: vcpkg build
        uses: johnwason/vcpkg-action@v7
        id: vcpkg
        with:
          triplet: x64-linux-release
          cache-key: ubuntu-latest
          revision: master
          token: ${{ github.token }}
          pkgs: opus
          # manifest-dir: ${{ github.workspace }}/src/sdk/lib/libmedia_codec
      - name: build wheel
        run: |
          cd src/sdk/lib/libmedia_codec
          python -m build -w
      - name: archive wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ runner.os }}-${{ runner.arch }}-py3.14
          path: src/sdk/lib/libmedia_codec/dist/*
          if-no-files-found: error



