name: Build
on:
  workflow_dispatch:
permissions:
  contents: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: dependencygraph
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: src/sdk
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: install deps
        run: pip install build
      - name: Bootstrap vcpkg
        shell: bash
        run: ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh
      # - name: Run vcpkg
      #   run: ${{ github.workspace }}/vcpkg/vcpkg install --dry-run
      - name: build wheel
        run: |
          cd src/sdk/lib/libmedia_codec
          python -m build -w
