name: Build
on:
  workflow_dispatch:
permissions:
  contents: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
jobs:
  wheel:
    strategy:
      matrix:
        config:
          - os: ubuntu-22.04
            vcpkg_triplet: x64-linux-release
          - os: ubuntu-22.04-arm
            vcpkg_triplet: arm64-linux-release
          - os: macos-15-intel
            vcpkg_triplet: x64-osx-release
          - os: macos-latest
            vcpkg_triplet: arm64-osx-release
          - os: windows-latest
            vcpkg_triplet: x64-windows-release
          - os: windows-11-arm
            vcpkg_triplet: arm64-windows-static-release
        python-version:
          - "3.13"
          - "3.14"
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: src/sdk
      - if: runner.os == 'Linux'
        name: install apt deps
        run: |
          sudo apt-get update
          sudo apt-get install nasm -y
      - if: runner.os == 'macOS'
        name: install apt deps
        run: |
          brew install nasm
      - name: vcpkg build
        uses: johnwason/vcpkg-action@v7
        id: vcpkg
        with:
          disable-cache: true
          triplet: ${{ matrix.config.vcpkg_triplet }}
          revision: master
          token: ${{ github.token }}
          manifest-dir: ${{ github.workspace }}/src/sdk/lib/libmedia_codec
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: install deps
        run: pip install build repairwheel
      - name: build wheel
        run: |
          cd src/sdk/lib/libmedia_codec
          python -m build -w --config-setting cmake.define.VCPKG_TARGET_TRIPLET=${{ matrix.config.vcpkg_triplet }}
          repairwheel -o repaired_dist dist/*.whl
      - name: archive wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ runner.os }}-${{ runner.arch }}-py${{ matrix.python-version }}
          path: src/sdk/lib/libmedia_codec/repaired_dist/*
          if-no-files-found: error
